name: Build and Test

on:
  push:
    branches: [ creati-aprile-main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: 20
    - name: Set up Maven
      uses: apache/maven@v2.2.1
    - name: Build with Maven
      run: mvn clean install
      env:
        SPRING_BOOT_VERSION: 3.0.1-SNAPSHOT
